const reqEvent = (event) => require(`../events/${event}`);//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
module.exports = client => {
  client.on('ready', () => reqEvent('ready')(client));//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
  client.on('message', reqEvent('message'));//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
};


////////// lord creative
//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative