const Discord = require('discord.js');//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
const ayarlar = require('../ayarlar.json');//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
const db = require('quick.db')//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative

module.exports = async message => {//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
  let client = message.client;//Lord Creat//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creativeive//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
  let prefix = ayarlar.prefix//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
  if (message.author.bot) return;//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
  if (!message.content.startsWith(prefix)) return;//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
  let command = message.content.split(' ')[0].slice(prefix.length);//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
  let params = message.content.split(' ').slice(1);
  let perms = client.elevation(message);//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
  let cmd;//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
  if (client.commands.has(command)) {//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
    cmd = client.commands.get(command);//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
  } else if (client.aliases.has(command)) {
    cmd = client.commands.get(client.aliases.get(command));//Lord Creative
  }
  if (cmd) {//Lord Creative//Lord Creative
    let karaliste = await db.fetch(`kullanicikaraliste_${message.author.id}`)//Lord Creative//Lord Creative
    if(karaliste) return//Lord Creative
    if (perms < cmd.conf.permLevel) return;//Lord Creative//Lord Creative//Lord Creative
    cmd.run(client, message, params, perms);//Lord Creative//Lord Creative//Lord Creative//Lord Creative
  }
//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative
};


////////// lord creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative//Lord Creative